[package]
name = "butterfly"
version = "0.2.0"
edition = "2024"

[dependencies]
libafl = { version = "0.15.3", features = ["prelude"] }
libafl_bolts = { version = "0.15.3", features = ["prelude"] }
serde = "1.0"
postcard = "1.0"
rand_core = "0.9"
smallvec = "1.15"
